- name: dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present

- name: dotdeb repo
  apt_repository: repo="deb http://packages.dotdeb.org wheezy all" state=present update_cache=yes

- name: dotdeb php55 repo
  apt_repository: repo="deb http://packages.dotdeb.org wheezy-php55 all" state=present update_cache=yes

- name: install nginx and php with dependencies
  apt: name=php5-cli state=latest

- name: set-up default timezone
  ini_file: >
    dest="/etc/php5/cli/php.ini"
    section="Date"
    option="date.timezone"
    value="UTC"
